El mito del Trol Anónimo / Issue #2
JaquerEspeis/privacidad-queer pull request #3
Opened 2018-05-01 19:31 UTC by nitos

Esta es la traducción del capítulo: El mito del Trol Anónimo por Violet Hargrave

2018-05-02 01:44 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Una gran abundancia de artículos nos dice que las redes sociales sufren de un gran "problema de troles".
Las primeras comillas en español son «», no ". Debería ser «problema de troles».

2018-05-08 23:25 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Hay un poco de confusión sobre realmente qué es tener un «problema de troles». Con personas privilegiadas que confunden porqué víctimas no pueden «ignorar un poco de personas gritando sin sentido a e
Esta parte la traduciría un poco diferente: «ignorar un poco de personas gritando sin sentido a ellas» = «ignorar a un poco de personas gritándoles cosas sin sentido»
sólo para callarlos = solo para callarlas

Utiliza pronombres femeninos o inclusivos en lugar de masculinos (política inclusiva del jaquerespeis)
amenazas de muerte a personas ancianas
protección a niñas 
hermanas/primas/niñas
empleadoras
bombardeada
callarlas

2018-05-08 23:26 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
>  Desafortunadamente, esta solución tan obvia no se acerca a la realidad de resolver estos problemas. Cualquier víctima de un ataque similar le dirá lo mismo y también sociólogos y expertos en prevensi
sociólogas, expertas

2018-05-08 23:29 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Primero que nada, los «trolls» no son anónimos. Hay varias técnicas en el arsenal de tácticas de un abusador serial que involucran registrar una gran cantidad de cuentas falsas y usarlas todas para e
las «trolls» no son anónimas -- podrías decir personas trolls si te sentías más cómodo
empleadas
expulsadas
organizadoras

2018-05-08 23:30 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
>  Aquellos que no tienen la inteligencia o el impulso para monetizar su odio necesitan sus nombres adjuntos para satisfacer sus egos. Twitter, en particular, está lleno de monstruos asquerosos que hace
aquellas personas que no tienen...
mujeres que han sido bloqueadas

2018-05-08 23:33 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Mientras tanto, son las víctimas de esos ataques que sufren más los esfuerzos de «combatir anomisidad». La [política de Facebook de nombres reales](https://en.wikipedia.org/wiki/Facebook_real-name_po
La [política de Facebook de nombres reales](https://en.wikipedia.org/wiki/Facebook_real-name_policy_controversy) es abusada para cerrar constantemente los perfiles de personas afrodescendientes...

 antes de hablar con amigas y familiares

a asombrosa cantidad de jugadoras trans se vio repentinamente expuesta

2018-05-08 23:41 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
>  ¿Cómo, entonces, uno podría preguntarse, estos nefastos acosadores evitan las consecuencias repetidamente de encabezar, si no con frecuencia, campañas de odio y abuso contra personas inocentes? ¿Camp
**una** podría preguntarse
como para poner fin **a** carreras
No es que sean **anónimas**
Tal vez sus alborotos no son una prioridad tan alta como **otras**

**los delincuentes que incurren en delitos menos y de primera vez** son mucho más propensos a ver que se tomen medidas contra ellos que los reincidentes de alto perfil.

2018-05-08 23:42 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Quizás entonces, ¿hay circunstancias atenuantes? ¿Excepciones para personas con gran fama sin relación a sus campañas de abuso? Eso sin duda explicaría por qué Persson recibe un pase, vendiendo la co
lista C que **dió** nombre

2018-05-08 23:45 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
>  Si ese fuera el caso, no dejaría a Brennan fuera del alcance. Toda su vida gira en torno a la persecución vengativa y peligrosa para la vida de las mujeres trans. Y sin duda no excusaría al verdadero
**Una** razonablemente asumiría que...

2018-05-08 23:48 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
>  Antes de su prohibición, Yiannopoulos fue el tema específico de muchas reuniones, discutiendo literalmente miles de casos bien definidos en los que exhibía comportamientos inaceptables según cualquie
completamente falsas de abuso de drogas y **peligro para** niñas

2018-05-08 23:49 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Los fundadores de Reddit han admitido, en discusiones públicas sobre sus operaciones internas, introducir «gold» como una forma de avivar las llamas del abuso en el sitio mientras se benefician de él
**Las fundadoras** de Reddit

2018-05-08 23:50 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
>  Facebook es notorio por permitir la intolerancia y [silenciar a los activistas](https://www.theguardian.com/technology/2016/sep/12/facebook-blocks-shaun-kingblack-lives-matter) a través de sus caract
silenciar a **las** activistas
**culpándolas** de los defectos

2018-06-11 21:30 UTC, nitos commented on el-mito-del-trol-anonimo.md
>  ¿Cómo, entonces, uno podría preguntarse, estos nefastos acosadores evitan las consecuencias repetidamente de encabezar, si no con frecuencia, campañas de odio y abuso contra personas inocentes? ¿Camp
por ejemplo este, en masculino: los delincuentes.

2018-06-11 21:35 UTC, dtec83 commented
Yo la tiraría a femenino tmb o neutral

El 11 de junio de 2018, 15:30, José Gutiérrez Álvarez<
notifications@github.com> escribió:

> *@nitos* commented on this pull request.
> ------------------------------
>
> In el-mito-del-trol-anonimo.md
> <https://github.com/JaquerEspeis/privacidad-queer/pull/3#discussion_r194554317>
> :
>
> >
>  ------
>
> -Tales esfuerzos para despojar a las víctimas de su anonimato (a menudo referido como "doxxing") frecuentemente se coordinan por medio de sitios dedicados de acecho, como [8chan's / baphomet / board](https://storify.com/a_man_in_black/baphomet), o [Kiwi Farms](http://nymag.com/selectall/2016/07/kiwi-farms-the-webs-biggest-community-ofstalkers.html). Los sitios de redes sociales rutinariamente se niegan a tratar los enlaces a estos sitios como acoso, afirmando que solo tienen jurisdicción sobre lo que ellos personalmente hospedan, pero tienen excusas similares cuando la información personal de las personas se expone directamente a través de sus servicios.
> +Tales esfuerzos para despojar a las víctimas de su anonimato (a menudo referido como «doxxing») frecuentemente se coordinan por medio de sitios dedicados de acecho, como [8chan's / baphomet / board](https://storify.com/a_man_in_black/baphomet), o [Kiwi Farms](http://nymag.com/selectall/2016/07/kiwi-farms-the-webs-biggest-community-ofstalkers.html). Los sitios de redes sociales rutinariamente se niegan a tratar los enlaces a estos sitios como acoso, afirmando que solo tienen jurisdicción sobre lo que ellos personalmente hospedan, pero tienen excusas similares cuando la información personal de las personas se expone directamente a través de sus servicios.
>
>  Personalmente, he estado inundada durante meses con tweets de usuarios que anuncian sus vínculos con Kiwi Farms, gritando nombres y adjuntando fotos de varias personas de las que creen que soy secretamente. Cuando informo sobre esto, la respuesta de Twitter es que solo eliminarán las publicaciones si puedo proporcionarles identificaciones con foto, demostrando que realmente soy cada uno de estos hombres al azar. Ahora se está acosando a inocentes al azar en un esfuerzo por atacarme, y la única acción que la plataforma está dispuesta a tomar sería confirmar a mis acosadores que finalmente adivinaron el nombre correcto si les proporcioné la verificación.
>
>  ¿Cómo, entonces, uno podría preguntarse, estos nefastos acosadores evitan las consecuencias repetidamente de encabezar, si no con frecuencia, campañas de odio y abuso contra personas inocentes? ¿Campañas tan severas como para poner fin carreras, obligar a las personas a esconderse y capturar la atención de los medios internacionales? No es que sean anónimos. Tal vez sus alborotos no son una prioridad tan alta como otros? No es el caso. Después de haber revisado personalmente decenas de miles de casos de abuso denunciado, los delincuentes por primera vez y menores son mucho más propensos a ver que se tomen medidas contra ellos que los reincidentes de alto perfil.
>
> por ejemplo este, en masculino: los delincuentes.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/JaquerEspeis/privacidad-queer/pull/3#discussion_r194554317>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ae3dCYgrFPyHMCII2-_87UoLNHxcz_Pqks5t7uFigaJpZM4TuYqV>
> .
>

2018-06-12 01:21 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Hay un poco de confusión sobre realmente qué es tener un «problema de troles». Con personas privilegiadas que confunden porqué víctimas no pueden «ignorar a un poco de personas gritándoles cosas sin
porqué -> por qué

2018-06-12 01:21 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Aunque estos aspectos que ponen en peligro la vida, que son temas delicados, y cuestan encontrarles soluciones fáciles como estar detrás de departamentos policiacos oxidados, o la animosidad de usar
emails -> correos electrónicos

2018-06-12 01:24 UTC, come-maiz commented on el-mito-del-trol-anonimo.md
> +Primero que nada, las personas «trolls» no son anónimas. Hay varias técnicas en el arsenal de tácticas de un abusador serial que involucran registrar una gran cantidad de cuentas falsas y usarlas tod
trolls -> troles
emails -> correos electrónicos

2018-06-12 01:28 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Aquellas personas que no tienen la inteligencia o el impulso para monetizar su odio necesitan sus nombres adjuntos para satisfacer sus egos. Twitter, en particular, está lleno de monstruos asquerosos
dedo puntiagudo -> dedo apuntando

2018-06-12 01:30 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Mientras tanto, son las víctimas de esos ataques que sufren más los esfuerzos de «combatir anomisidad». La [política de Facebook de nombres reales](https://en.wikipedia.org/wiki/Facebook_real-name_po
anomisidad -> anonimidad
lidiar que -> lidiar con que

2018-06-12 01:31 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Esto a su vez se relaciona con los aspectos más peligrosos de los «problemas de troles». Incluso sin la ayuda de políticas de nombres reales, descubrir las informaciones de contacto de las víctimas p
trolls -> troles
sexualmente abusando de -> de abusar sexualmente a

2018-06-12 01:34 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +¿Cómo, entonces, una podría preguntarse, estos nefastos acosadores evitan las consecuencias repetidamente de encabezar, si no con frecuencia, campañas de odio y abuso contra personas inocentes? ¿Camp
poner fin carreras -> poner fin a carreras

2018-06-12 01:41 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +La triste verdad del asunto es que los sitios de redes sociales disfrutan activamente albergando este tipo de campañas de acoso en serie. Públicamente, por supuesto, constantemente hacen declaracione
troles

2018-06-12 01:42 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Sin embargo, como sucede, no necesitamos especular. Confidencialmente me impiden entrar en detalles, pero los detalles de las reuniones llevadas a cabo dentro de estas «asociaciones» revelan qué tipo
la razones -> las razones

2018-06-12 01:43 UTC, elopio commented on el-mito-del-trol-anonimo.md
> +Las fundadoras de Reddit han admitido, en discusiones públicas sobre sus operaciones internas, introducir «gold» como una forma de avivar las llamas del abuso en el sitio mientras se benefician de él
al blanco supremacía -> a la supremacía blanca

2018-06-12 01:45 UTC, come-maiz requested changes
Gracias nitos. Quedan unos pequeños errores.
Y por ahora, yo creo que es mejor poner los pies de página explícitos, porque si no se va a hacer un desmadre con los números.
Busque <sup> en las traducciones ya aceptadas.

2018-08-03 02:18 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Primero que nada, las personas «trolls» no son anónimas. Hay varias técnicas en el arsenal de tácticas de un abusador serial que involucran registrar una gran cantidad de cuentas falsas y usarlas tod
@nitos pendiente acá

2018-08-03 02:19 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Hay un poco de confusión sobre realmente qué es tener un «problema de troles». Con personas privilegiadas que confunden porqué víctimas no pueden «ignorar a un poco de personas gritándoles cosas sin
@nitos pendiente acá

2018-08-03 02:19 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Aunque estos aspectos que ponen en peligro la vida, que son temas delicados, y cuestan encontrarles soluciones fáciles como estar detrás de departamentos policiacos oxidados, o la animosidad de usar
@nitos pendiente

2018-08-03 04:44 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Hay un poco de confusión sobre realmente qué es tener un «problema de troles». Con personas privilegiadas que confunden porqué víctimas no pueden «ignorar a un poco de personas gritándoles cosas sin
Listo

2018-08-03 04:44 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Aunque estos aspectos que ponen en peligro la vida, que son temas delicados, y cuestan encontrarles soluciones fáciles como estar detrás de departamentos policiacos oxidados, o la animosidad de usar
Listo

2018-08-03 04:48 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Primero que nada, las personas «trolls» no son anónimas. Hay varias técnicas en el arsenal de tácticas de un abusador serial que involucran registrar una gran cantidad de cuentas falsas y usarlas tod
Listo

2018-08-03 04:50 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Aquellas personas que no tienen la inteligencia o el impulso para monetizar su odio necesitan sus nombres adjuntos para satisfacer sus egos. Twitter, en particular, está lleno de monstruos asquerosos
Listo

2018-08-03 04:55 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Mientras tanto, son las víctimas de esos ataques que sufren más los esfuerzos de «combatir anomisidad». La [política de Facebook de nombres reales](https://en.wikipedia.org/wiki/Facebook_real-name_po
Listo

2018-08-03 04:58 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Esto a su vez se relaciona con los aspectos más peligrosos de los «problemas de troles». Incluso sin la ayuda de políticas de nombres reales, descubrir las informaciones de contacto de las víctimas p
Listo

2018-08-03 05:02 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +¿Cómo, entonces, una podría preguntarse, estos nefastos acosadores evitan las consecuencias repetidamente de encabezar, si no con frecuencia, campañas de odio y abuso contra personas inocentes? ¿Camp
Listo

2018-08-03 05:06 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +La triste verdad del asunto es que los sitios de redes sociales disfrutan activamente albergando este tipo de campañas de acoso en serie. Públicamente, por supuesto, constantemente hacen declaracione
Listo

2018-08-03 05:12 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Sin embargo, como sucede, no necesitamos especular. Confidencialmente me impiden entrar en detalles, pero los detalles de las reuniones llevadas a cabo dentro de estas «asociaciones» revelan qué tipo
Listo

2018-08-03 05:14 UTC, dtec83 commented on el-mito-del-trol-anonimo.md
> +Las fundadoras de Reddit han admitido, en discusiones públicas sobre sus operaciones internas, introducir «gold» como una forma de avivar las llamas del abuso en el sitio mientras se benefician de él
Listo

2018-08-03 05:45 UTC, merged